import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const flexo = localFont({
  src: [
    {
      path: './fonts/Flexo-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Flexo-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Flexo-Demi.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/Flexo-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-flexo',
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${flexo.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
